[package]
name = "secp256k1"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "secp256k1"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.0"
lazy_static = "1.0"
libsecp256k1 = "0.3.4"
rand = "0.7.3"
